export const SET_SHORT_URL = "SET_SHORT_URL"
export const GET_SHORT_URL_REQUEST = "GET_SHORT_URL_REQUEST"

export const SET_LIST_OF_URL = "SET_LIST_OF_URL"
export const GET_LIST_OF_URL_REQUEST = "GET_LIST_OF_URL_REQUEST"

export const SET_TOTAL_COUNT = 'SET_TOTAL_COUNT'
