version: "3"

services:
  main:
    container_name: main
    build:
      context: .
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${PORT}:3030
    command: npm run start
    depends_on:
      - redis
    restart: always

  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ~/redis:/data
